server:
  port: 9393

logging:
  level:
    org.apache.kafka.clients: ERROR

spring:
  application:
    name: file-service
  profiles:
    active: default
  data:
    mongodb:
      database: ${DATABASE_MONGO_NAME:default_db}
      uri: ${DATABASE_MONGO_URL:mongodb://gen_user:itmPlatformNosqlStorage@212.113.121.37:27017/?authSource=admin}
      uuid-representation: standard
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  kafka:
    bootstrap-servers: ${KAFKA_URL:http://localhost:9092}
    consumer:
      group-id: file-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: latest
      auto-commit-interval: 100ms
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
    topic:
      file-events: file-events
      cv-events: cv-events
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.dev.advice.it-mentor.space/realms/ITM-Advice

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    config-url: /${spring.application.name}/v3/api-docs/swagger-config
    url: /${spring.application.name}/v3/api-docs

attachment:
  cleanup:
    cron: "0 0 2 * * ?"

cv:
  cleanup:
    cron: "0 0 2 * * ?"

image:
  cleanup:
    cron: "0 0 2 * * ?"
